"""initial schema

Revision ID: 17b6ba1a84c7
Revises: 
Create Date: 2026-08-19 10:56:57.622374

"""
from alembic import op
import sqlalchemy as sa


revision = '17b6ba1a84c7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('media_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('source_path', sa.String(length=4096), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('frame_rate', sa.Float(), nullable=False),
    sa.Column('frame_count', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('pixel_format', sa.String(length=32), nullable=True),
    sa.Column('color_space', sa.String(length=32), nullable=True),
    sa.Column('transfer', sa.String(length=32), nullable=True),
    sa.Column('codec_name', sa.String(length=64), nullable=True),
    sa.Column('timecode_format', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('media_assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_media_assets_project_id'), ['project_id'], unique=False)

    op.create_table('shots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('start_frame', sa.Integer(), nullable=False),
    sa.Column('end_frame', sa.Integer(), nullable=False),
    sa.Column('start_timecode', sa.String(length=16), nullable=False),
    sa.Column('end_timecode', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['media_assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'index', name='uq_shot_asset_index')
    )
    with op.batch_alter_table('shots', schema=None) as batch_op:
        batch_op.create_index('ix_shots_asset_frames', ['asset_id', 'start_frame', 'end_frame'], unique=False)
        batch_op.create_index(batch_op.f('ix_shots_asset_id'), ['asset_id'], unique=False)

    op.create_table('corrections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shot_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['shot_id'], ['shots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('corrections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_corrections_shot_id'), ['shot_id'], unique=False)

    op.create_table('frame_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shot_id', sa.Integer(), nullable=False),
    sa.Column('frame_index', sa.Integer(), nullable=False),
    sa.Column('luma_min', sa.Float(), nullable=True),
    sa.Column('luma_p5', sa.Float(), nullable=True),
    sa.Column('luma_mean', sa.Float(), nullable=True),
    sa.Column('luma_median', sa.Float(), nullable=True),
    sa.Column('luma_p95', sa.Float(), nullable=True),
    sa.Column('luma_max', sa.Float(), nullable=True),
    sa.Column('luma_std', sa.Float(), nullable=True),
    sa.Column('r_mean', sa.Float(), nullable=True),
    sa.Column('g_mean', sa.Float(), nullable=True),
    sa.Column('b_mean', sa.Float(), nullable=True),
    sa.Column('saturation_mean', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['shot_id'], ['shots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('frame_metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_frame_metrics_shot_id'), ['shot_id'], unique=False)

    op.create_table('representative_frames',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shot_id', sa.Integer(), nullable=False),
    sa.Column('frame_index', sa.Integer(), nullable=False),
    sa.Column('timecode', sa.String(length=16), nullable=False),
    sa.Column('image_path', sa.String(length=4096), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['shot_id'], ['shots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shot_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('representative_frames')
    with op.batch_alter_table('frame_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_frame_metrics_shot_id'))

    op.drop_table('frame_metrics')
    with op.batch_alter_table('corrections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_corrections_shot_id'))

    op.drop_table('corrections')
    with op.batch_alter_table('shots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shots_asset_id'))
        batch_op.drop_index('ix_shots_asset_frames')

    op.drop_table('shots')
    with op.batch_alter_table('media_assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_media_assets_project_id'))

    op.drop_table('media_assets')
    op.drop_table('projects')
    # ### end Alembic commands ###
