"""add skin metrics

Revision ID: 3336e58df071
Revises: 17b6ba1a84c7
Create Date: 2026-08-19 11:28:49.741655

"""
from alembic import op
import sqlalchemy as sa


revision = '3336e58df071'
down_revision = '17b6ba1a84c7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skin_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shot_id', sa.Integer(), nullable=False),
    sa.Column('face_index', sa.Integer(), nullable=False),
    sa.Column('mean_b', sa.Float(), nullable=False),
    sa.Column('mean_g', sa.Float(), nullable=False),
    sa.Column('mean_r', sa.Float(), nullable=False),
    sa.Column('sample_pixels', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['shot_id'], ['shots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shot_id', 'face_index', name='uq_skin_shot_face')
    )
    with op.batch_alter_table('skin_metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_skin_metrics_shot_id'), ['shot_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skin_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_skin_metrics_shot_id'))

    op.drop_table('skin_metrics')
    # ### end Alembic commands ###
