"""add subjects and editable face grouping

Revision ID: b494e149e8b0
Revises: 3336e58df071
Create Date: 2026-08-19 11:44:36.818100

"""
from alembic import op
import sqlalchemy as sa


revision = 'b494e149e8b0'
down_revision = '3336e58df071'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('reference_shot_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['media_assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reference_shot_id'], ['shots.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subjects_asset_id'), ['asset_id'], unique=False)

    with op.batch_alter_table('skin_metrics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_skin_metrics_subject_id'), ['subject_id'], unique=False)
        batch_op.create_foreign_key('fk_skin_metrics_subject_id', 'subjects', ['subject_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skin_metrics', schema=None) as batch_op:
        batch_op.drop_constraint('fk_skin_metrics_subject_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_skin_metrics_subject_id'))
        batch_op.drop_column('subject_id')

    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subjects_asset_id'))

    op.drop_table('subjects')
    # ### end Alembic commands ###
